# Generated by Django 4.0.4 on 2022-06-08 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=5000),
            preserve_default=False,
        ),
    ]
